services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=your_secret_key-here
      - DATABASE_URL=postgreSql://postgres:postgres@db:5432/postgres

  db:
    image: postgres:13

    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
