# Generated by Django 4.2.7 on 2025-05-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
