# Generated by Django 4.2.7 on 2025-05-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='referencia',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
