# Generated by Django 4.2.7 on 2025-05-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_producto_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
