# Generated by Django 4.2.7 on 2025-05-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_producto_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='referencia',
        ),
    ]
